### ISSUE TITLE
Abysmally slow downloads

### ISSUE THREAD

**Issue by silversword411** [brogers5/chocolatey-package-foxitreader#1]
Download speeds thru choco are abysmal for me. 
choco download at 50KB/sec, direct downloads at 100MB/sec
Looks like the URL for choco is:
https://www.foxit.com/downloads/latest.html?product=Foxit-Reader&platform=Windows&package_type=exe&language=German&version=11.1.0.52543
But website which is fast for me is: https://www.foxit.com/downloads/latest.html?product=Foxit-Reader&platform=Windows&version=&package_type=&language=English&distID= 

Is there something that can be done to change the URL used, or figure out why foxit is throttling choco? It seems deliberate, but maybe I'm missing something.

**Comment by brogers5** [comment]
I had the same download experience while I was preparing the recently updated package, and when downloading via Foxit's official updater, so I doubt it's Foxit deliberately throttling downloads via Chocolatey. Since Foxit officially released the update yesterday, I would not be surprised if the server hosting the installer binary is getting hammered with download requests. Perhaps things will improve once the initial rush dies down.

The complication with the proposed URL change is that a different binary is served for the "English" language variant, so an outright replacement would break the package's L10N support. The package specifically targets the "German" variant to support multiple languages in one installer. I suspect these two binaries are being served by different CDN nodes, which would explain the speed discrepancy.

From what I can see, the [Firefox package](https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/firefox) solves this by grabbing a language-specific installer. Perhaps a similar approach is in order for this package.

I'll see what I can do about it this weekend. Until then, pull requests are always welcome if you're in a position to help.

**Comment by brogers5** [comment]
I had an opportunity to test the download speed again on my work PC. In so doing, I noticed the download speed has since improved considerably, to the point I'd consider it acceptable. Assuming this continues to be the case, I'm currently leaning toward delaying rollout until the next software release. I'll consider making a package fix version if there's enough user interest.

**Comment by jsreynolds** [comment]
I wonder why the language states "German" ?

**Comment by brogers5** [comment]
@jsreynolds, Foxit distributes multiple installer binaries, of which only one of them is currently grabbed and used by the Chocolatey package. On [their website](https://www.foxit.com/downloads/#Foxit-Reader/), one would normally be prompted to select a specific language from a drop-down menu before starting the download.

![image](https://user-images.githubusercontent.com/6869577/137424250-60fd6e8c-122b-480b-856e-79828eae69c8.png)

The user's language selection is reflected as a URL query parameter in the request. Many of these language options will prompt the server to respond by serving a single binary supporting a concept known as localization (i.e. L10N), which is reflected in the installer filename downloaded by [the install script](https://github.com/brogers5/chocolatey-package-foxitreader/blob/main/tools/chocolateyInstall.ps1). German just so happens to be one of those options, and was chosen by the previous maintainer of this package.

The package essentially implements the following approach to localization [as described in Chocolatey's official package creation guide](https://docs.chocolatey.org/en-us/create/create-packages#internationalization-and-localization-of-packages):

> Sometimes an application installer or executable has already integrated all supported languages, but doesn't automatically select the system language during a silent install. Often you can pass an additional install parameter to select the desired language. This is used for example in the [CCleaner](https://community.chocolatey.org/packages/ccleaner) package ([source code](https://github.com/tonigellida/chocolateyautomaticpackages/tree/master/ccleaner)).

If you ran the installer binary manually, or executed `choco install foxitreader --not-silent`, the first window shown prompts the user to select their preferred language from multiple options:

![image](https://user-images.githubusercontent.com/6869577/137426277-ca060bf9-2f71-41cd-816b-455b71389edc.png)

The package creation guide is accurate in stating that language selection is handled by passing an additional command-line argument set from Chocolatey's perspective. Examples for this feature are available in the [package's description](https://github.com/brogers5/chocolatey-package-foxitreader/blob/main/DESCRIPTION.md).

For anyone who requires this specific binary, there's unfortunately not a lot I can do about a slow server without acquiring redistribution rights - that's on Foxit themselves to fix. But for others who would settle for another binary that gets served more quickly, I can certainly understand the frustration in being forced to download this one.

Hope this helps to clarify things.

**Comment by jsreynolds** [comment]
@brogers5 Wow - thank you so much for the comprehensive reply. Much appreciated!

**Comment by silversword411** [comment]
Gonna close, and I guess we'll monitor and hope for the best

**Comment by jeansagi** [comment]
This issue should not be closed!

Download times still are really **ABISMAL**.


J.

**Comment by brogers5** [comment]
Unfortunately, download speeds indeed appear to have regressed once again. Reopening since this is still problematic.

Until I can get a package update out, I would encourage affected users to reach out to Foxit support. This issue is reproducible outside of Chocolatey and deals with their official distribution point for non-English L10N-supported releases. Even a package update won't solve the issue for those unwilling to use the English language binary.

**Comment by brogers5** [comment]
Took a little bit of time tonight to dig into the English language installer.

Part of the reason the initial download completes quickly is that this is constructed and packaged in a substantially different manner. This is a small web-based installer built with dotSetup, which presumably completes the actual download during runtime.

It also behaves differently from the L10N binary historically used by this package, which was built with Inno Setup. Notably, it is not honoring Foxit's [documented silent install arguments](https://kb.foxitsoftware.com/hc/en-us/articles/360042663971-Foxit-Reader-EXE-Installer-Public-Properties-). I suspect this is older documentation that is referring to the Inno Setup installer instead. This is leaving me concerned that anyone wanting to use this particular installer may be forced into feature regressions. 

I've created a support ticket with Foxit to confirm whether this installer supports a silent install, and if so, the proper procedure to invoke it. If not, we may need to take a dependency on [`autohotkey`](https://community.chocolatey.org/packages/autohotkey) to work around it, and create an AHK script that is conditionally invoked only for this installer.

Assuming this installer also does not have feature parity, it's likely that I will also need to add a package-specific parameter to force use of the L10N binary, to provide a path for backward-compatibility. We're already looking at making a breaking change here, so I'd like to do what I can to minimize the potential impact.

**Comment by krazykenny** [comment]
i find that it always seems to resolve to using the cdn01 server to download which is slow all of the time.
On experimenting using a download manager like FDM, changing the url so that it uses cdn06 was super fast. That cdn seems to be hosted with cloudflare. Perhaps telling it to somehow use the cdn06 server could be a solution?
I also found download speed using cdn09 server was also pretty good, but cdn06 was super quick. cdn01 and cdn02 servers just super slow.
https://cdn06.foxitsoftware.com/product/reader/desktop/win/11.1.0/FoxitPDFReader111_L10N_Setup_Prom.exe

**Comment by brogers5** [comment]
Theoretically, a request to the canonical URL that's already used by the package _should_ prompt Foxit's server to respond with a redirect to the appropriate CDN node. I imagine this would be taking factors like geolocation, load balancing, failover, etc. into account that the package would not have visibility to.

I'm hesitant to override that and funnel all of the package's traffic toward a specific CDN node, but If Foxit can't resolve this soon, I might just do it anyway in the interest of getting a short-term fix out there.

**Comment by brogers5** [comment]
I am still observing inconsistent download speeds with `cdn01`. Seeing as the release has been out for well over 2 weeks now with no sign of improving, I feel we're at a point where @krazykenny's suggestion seems appropriate. I'll be pushing a package fix version that implements it soon.

**Comment by silversword411** [comment]
It's really been this way for months, thx for looking at this everyone!
